#!/usr/bin/bash

if [ "$1" == '-h' -o "$1" == '--help' -o $# -ne 3 ]; then
    cat << EOF
Usage:
    $(basename $0) <groupId> <artifactId> <version>

EOF
    exit 0
fi

groupid=$1
artifactid=$2
version=$3

maven_repository="$HOME/.m2/repository"
group_path="$(echo "$groupid" | tr . /)"
jar_name="${artifactid}-${version}.jar"

jar_path="$maven_repository/$group_path/${artifactid}/$jar_name"

output="$(javap -v -classpath "$jar_path" module-info | grep -E '^  (minor|major) version: [0-9]+$')"

minor="$(echo "$output" | grep -oE 'minor version: [0-9]+' | grep -oE '[0-9]+')"
major="$(echo "$output" | grep -oE 'major version: [0-9]+' | grep -oE '[0-9]+')"

bytecode_version="$major.$minor"

java_version=$([ $major -ge 45 -a $major -le 48 ] && echo "1.")$(($major - 44))

# TODO Flags to control this output
echo "Bytecode version: $bytecode_version"
echo "Java version: $java_version"
