#!/bin/env bash

[ $# -eq 0 ] && exit 0

if [ "$1" == '-h' -o "$1" == '--help' ]; then
    cat << EOF
Uso: jira <numeros dos cards>

Abre issues no Jira da via. Passar o número do card, ex: CAT-32
É permitido passar mais de um card, cada card será aberto uma aba separada do browser
É possível selecionar o browser que abrirá a issue através da variável de ambiente \$BROWSER
Caso \$BROWSER não esteja definida o firefox será usado

Caso o gerenciador de janelas seja o i3 o foco mudará automaticamente para o browser
EOF

    exit 0
fi


for jira_key in "$@"
do
    ${BROWSER:-firefox} --new-tab "https://jira.viavarejo.com.br/browse/${jira_key}" &
done

which i3-msg &> /dev/null && i3-msg '[ class="^firefox$" ] focus' &> /dev/null

