#!/usr/bin/bash

[ "$1" == '-h' -o "$1" == '--help' ] && {
  cat << EOF
Usage: $(basename $0)

List all deployment configs on all namespaces
EOF
  exit 0
}

for namespace in $(oc projects -q); do
  oc get deploymentconfigs.apps.openshift.io \
    --namespace=$namespace \
    --no-headers=true \
    --output custom-columns="NAMESPACE:.metadata.namespace,NAME:.metadata.name"
done

