#!/usr/bin/env python3
import sys


def secsto8601(secs):
    UNITS = [
                # (suffix, seconds in unit, units in next unit)
                ('S', 1, 60),
                ('M', 60, 60),
                ('H', 60*60, 24),
                ('D', 60*60*24, 7),
                ('W', 60*60*24*7, 4),
                ('M', 60*60*24*7*4, 12),
                ('Y', 60*60*24*7*4*12, None),
            ]

    tokens = list()
    for suffix, secs_in_unit, units_in_next in UNITS:
        units = int(secs/secs_in_unit)
        if units_in_next:
            units = units % units_in_next
        tokens.append(f'{units}{suffix}' if units > 0 else '')

    tokens.reverse()

    date = ''.join(tokens[:-3])

    time = ''.join(tokens[-3:])
    time = f'T{time}' if time else ''

    return f'P{date}{time}'


try:
    secs = int(sys.argv[1])
    print(secsto8601(secs))
except:
    pass

# def test(name, expected, action):
#     actual = action()
# 
#     if actual == expected:
#         print(f'{name}: OK')
#     else:
#         print(f'{name}: ERROR ("{actual}" != "{expected}")')
# 
# 
# def tests():
#     the_tests = [
#         ('1seg', 'PT1S', 1),
# 
#         ('1min - 1seg', 'PT59S', 59),
#         ('1min', 'PT1M', 60),
#         ('1min + 1seg', 'PT1M1S', 61),
# 
#         ('1hor - 1seg', 'PT59M59S', 3600-1),
#         ('1hor', 'PT1H', 3600),
#         ('1hor + 1seg', 'PT1H1S', 3601),
# 
#         ('1day - 1seg', 'PT23H59M59S', 86400-1),
#         ('1day', 'P1D', 86400),
#         ('1day + 1seg', 'P1DT1S', 86401),
# 
#         ('1sem - 1seg', 'P6DT23H59M59S', 604800-1),
#         ('1sem', 'P1W', 604800),
#         ('1sem + 1seg', 'P1WT1S', 604801),
# 
#         ('1mes - 1seg', 'P3W6DT23H59M59S', 2419200-1),
#         ('1mes', 'P1M', 2419200),
#         ('1mes + 1seg', 'P1MT1S', 2419201),
# 
#         ('1ano - 1seg', 'P11M3W6DT23H59M59S', 29030400-1),
#         ('1ano', 'P1Y', 29030400),
#         ('1ano', 'P1YT1S', 29030401),
#     ]
# 
#     for name, expected, param in the_tests:
#         test(name, expected, lambda: secsto8601(param))
