#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from sys import exit
from argparse import ArgumentParser, ArgumentError


def numbers_only(s: str) -> bool:
    from re import match

    return match('[0-9]+', s) is not None


def str_list(raw: str) -> list:
    raw_list = raw.split(',')

    for item in raw_list:
        if not numbers_only(item):
            return None

    return raw_list


def sku_list(raw: str) -> str:
    if not (result := str_list(raw)):
        raise ArgumentError('Invalid SKU list format, it must be a comma separated list where each item must contain numbers only')

    return result


# milestone A
# def filial_list(raw: str) -> list:
#     if not (result := str_list(raw)):
#         raise ArgumentError('Invalid filial list format, it must be a comma separated list where each item must contain numbers only')
# 
#     return result


def parse_command_line():
    parser = ArgumentParser(
        description='Return the status for one or more skus')

    parser.add_argument('skus',
                        type=sku_list,
                        help='SKU number, must contain only numbers')

    # milestone C
    # parser.add_argument('--environment',
    #                     '-e',
    #                     choices=['sit', 'hlg', 'stg', 'prd'],
    #                     default='prd',
    #                     help='Filial number list, comma separated')

    # milestone A
    # parser.add_argument('--filiais',
    #                     '-f',
    #                     type=filial_list,
    #                     help='Filial number list, comma separated')

    return parser.parse_args()


def main():
    global args

    args = parse_command_line()

    for sku in args.skus:
        print(f'Checking SKU {sku}')

    # Milestone 1
    # Find no Mongo catalogo/produtos
    # Select no DB2 mcr

    # Milestone A
    # Mongo: catalogo/estoque (se --filiais)
    # DB2: mcr_eqt (se --filiais)
    # Solr (se --filiais)
    # Mongo: Checar adm/filial implantada=true e ativa=true

    # Milestone B
    # Verificar se retorna na vv-vitrine
    # Verificar se retorna no vv-catalogo


    # Milestone D
    # Parâmetro para retornar flags da filial no Mongo em adm/filial/implantacoes

    return 0


if __name__ == '__main__':
    returncode = main() or 0

    exit(returncode)
