-- MERCADORIA

SELECT
	'QTD alteração de filial_comercialização - CMC_FIL',
	count(*)
FROM
	nsvp.CMC_fil
WHERE
	CD_EMPGCB = 21
	AND date(dt_mod)= CURRENT date
	AND time(dt_mod) BETWEEN '14:00:00' AND '15:00:00'
;

SELECT
	'QTD alteração de SKU_comercialização - MCR_CMC',
	count(*) AS Qtd
FROM
	nsvp.MCR_CMC a
WHERE
	CD_EMPGCB = 21
	AND date(dt_mod)= CURRENT date
	AND time(dt_mod) BETWEEN '14:00:00' AND '15:00:00'

;

SELECT
	'QTD alteração na comercialização - CMC',
	COUNT(*)
FROM
	nsvp.cmc
WHERE
	date(dt_mod) = CURRENT DATE
	AND time(dt_mod) BETWEEN '14:00:00' AND '15:00:00'
;

SELECT
	'QTD atualização de Preço_SKU(Filial) - HTR_PCO_MCR_ALT',
	COUNT(*)
FROM
	nsvp.MCR_CMC T1,
	nsvp.CMC_TIP_AGP_VLD T2,
	nsvp.BND_CMC T3,
	nsvp.MCR T4,
	nsvp.HTR_PCO_MCR_ALT T5,
	nsvp.CMC T6,
	nsvp.cmc_fil t7
WHERE
	T1.CD_EMPGCB = T2.CD_EMPGCB
	AND T1.CD_EMPGCB = T3.CD_EMPGCB
	AND T1.CD_EMPGCB = T6.CD_EMPGCB
	AND T1.CD_EMPGCB = T5.CD_EMPGCB_OPR
	AND t6.cd_cmc = t7.cd_cmc
	AND t6.cd_empgcb = t7.cd_empgcb
	AND T7.DT_CMCFIL_INI_VIG <= CURRENT date + 0 DAY
	AND (T7.DT_CMCFIL_FIM_VIG >= CURRENT date + 0 DAY
		OR T7.DT_CMCFIL_FIM_VIG IS NULL)
	AND T1.CD_CMC = T2.CD_CMC
	AND T1.CD_CMC = T3.CD_CMC
	AND T1.CD_CMC = T6.CD_CMC
	AND T1.CD_MCR = T4.CD_MCR
	AND T1.CD_MCR = T5.CD_MCR
	AND T1.CD_MCR BETWEEN 000000000 AND 9999999999
	AND T1.CD_CMC BETWEEN 0 AND 9999999
	AND T5.CD_TIPPCO = T6.CD_TIPPCO
	AND T1.CD_EMPGCB = 21
	AND T2.CD_TAVCMC = 3
	AND T3.CD_BND IN (1, 2)
	AND t4.st_mcr_svv = 'S'
	AND T1.DT_MCRCMC_INI_VIG <= CURRENT date + 0 DAY
	AND (T1.DT_MCRCMC_FIM_VIG >= CURRENT date + 0 DAY
		OR
                 T1.DT_MCRCMC_FIM_VIG IS NULL)
	AND T5.DT_PCOMCR_INI_VIG = CURRENT date + 0 DAY
	AND DATE(T5.DT_MOD) = CURRENT DATE
	AND TIME(T5.DT_MOD) BETWEEN '14:00:00' AND '15:00:00'
	AND T5.TS_HPMALT IN (
	SELECT
		TS_HPMALT
	FROM
		nsvp.HTR_PCO_MCR_ALT G
	WHERE
		G.CD_EMPGCB_OPR = T5.CD_EMPGCB_OPR
		AND G.CD_TIPPCO = T5.CD_TIPPCO
		AND G.CD_MCR = T5.CD_MCR
		AND G.DT_PCOMCR_INI_VIG = CURRENT date + 0 DAY
	ORDER BY
		G.DT_PCOMCR_INI_VIG DESC,
		G.TS_HPMALT DESC
                       FETCH FIRST 1 ROW ONLY )
;


SELECT
	'QTD atualização de Preço_SKU(Padrão) - HTR_PCO_MCR_ALT',
	count(*)
FROM
	nsvp.MCR_CMC T1,
	nsvp.CMC_TIP_AGP_VLD T2,
	nsvp.BND_CMC T3,
	nsvp.MCR T4,
	nsvp.HTR_PCO_MCR_ALT T5,
	nsvp.CMC T6
WHERE
	T1.CD_EMPGCB = T2.CD_EMPGCB
	AND T1.CD_EMPGCB = T3.CD_EMPGCB
	AND T1.CD_EMPGCB = T6.CD_EMPGCB
	AND T1.CD_EMPGCB = T5.CD_EMPGCB_OPR
	AND T1.CD_CMC = T2.CD_CMC
	AND T1.CD_CMC = T3.CD_CMC
	AND T1.CD_CMC = T6.CD_CMC
	AND T1.CD_MCR = T4.CD_MCR
	AND T1.CD_MCR = T5.CD_MCR
	AND T1.CD_MCR BETWEEN 000000000 AND 9999999999
	AND T1.CD_CMC BETWEEN 0 AND 9999999
	AND T5.CD_TIPPCO = T6.CD_TIPPCO
	AND T1.CD_EMPGCB = 21
	AND T2.CD_TAVCMC = 2
	AND T3.CD_BND IN (1, 2)
	AND t4.st_mcr_svv = 'S'
	AND T1.DT_MCRCMC_INI_VIG <= CURRENT date + 0 DAY
	AND (T1.DT_MCRCMC_FIM_VIG >= CURRENT date + 0 DAY
		OR
                 T1.DT_MCRCMC_FIM_VIG IS NULL)
	AND T5.DT_PCOMCR_INI_VIG = CURRENT date + 0 DAY
	AND DATE(T5.DT_MOD) = CURRENT DATE
	AND TIME(T5.DT_MOD) BETWEEN '14:00:00' AND '15:00:00'
	AND T5.TS_HPMALT IN (
	SELECT
		TS_HPMALT
	FROM
		nsvp.HTR_PCO_MCR_ALT G
	WHERE
		G.CD_EMPGCB_OPR = T5.CD_EMPGCB_OPR
		AND G.CD_TIPPCO = T5.CD_TIPPCO
		AND G.CD_MCR = T5.CD_MCR
		AND G.DT_PCOMCR_INI_VIG = CURRENT date + 0 DAY
	ORDER BY
		G.DT_PCOMCR_INI_VIG DESC,
		G.TS_HPMALT DESC
                       FETCH FIRST 1 ROW ONLY )
            ;
