-- Verifica se é mercadoria
SELECT CD_MCR , DS_MCR, CD_TSMCR , ST_MCR_LOJ_VRT , ST_MCR_SON , ST_MCR_SVV, ST_MCR_PEG_LEV
FROM nsvp.MCR
WHERE CD_MCR IN (4936280) -- Código do SKU
WITH UR;

-- Verifica se é conjunto
SELECT AMAM.CD_AMANC, M.CD_MCR, M.DS_MCR, M.CD_TSMCR , M.ST_MCR_LOJ_VRT , M.ST_MCR_SON , M.ST_MCR_SVV, M.ST_MCR_PEG_LEV
FROM NSVP.AGP_MCR_ANC_MCR amam
INNER JOIN NSVP.MCR M
ON AMAM.CD_MCR = M.CD_MCR
WHERE AMAM.CD_AMANC IN (4936280) -- Código do conjunto
ORDER BY 1, 2
WITH UR;

-- Verifica se é conjunto (forma mais simples)
select * from nsvp.agp_mcr_anc where cd_amanc in (4936280); 


--Para uma mercadoria (não conjunto) lista o código de comercialização
SELECT
    t1.cd_mcr,
    T1.CD_CMC,
    T1.DT_MCRCMC_INI_VIG,
    T1.DT_MCRCMC_FIM_VIG,
    t1.dt_mod,
    t5.cd_tippco,
    t3.cd_bnd
FROM
    NSVP.MCR_CMC T1,
    NSVP.CMC_TIP_AGP_VLD T2,
    NSVP.BND_CMC T3,
    NSVP.cmc t5,
    NSVP.mcr t6
WHERE
    T1.CD_MCR = 4936280
    AND T1.CD_EMPGCB = 21
    AND T1.DT_MCRCMC_INI_VIG <= CURRENT DATE
    AND (T1.DT_MCRCMC_FIM_VIG IS NULL
        OR T1.DT_MCRCMC_FIM_VIG >= CURRENT DATE)
    AND T2.CD_CMC = T1.CD_CMC
    AND T2.CD_EMPGCB = T1.CD_EMPGCB
    AND T2.CD_TAVCMC IN (1, 2)
    AND T3.CD_BND IN (1, 2)
    AND T3.CD_EMPGCB = T2.CD_EMPGCB
    AND T3.CD_CMC = T2.CD_CMC
    AND t5.cd_empgcb = t1.cd_empgcb
    AND t5.cd_cmc = t1.cd_cmc
    AND t6.cd_mcr = t1.cd_mcr
    AND t6.cd_tsmcr = 'A'
WITH UR;

-- Verifica estoque de uma mercadoria para uma filial
SELECT
	CD_EMPGCB AS EMPRESA,
	CD_FIL AS FILIAL,
	CD_MCR AS SKU,
	QT_EMCFIL_NOV AS LOJA,
	QT_EMCFIL_RSR_VND AS RESERVADO,
	QT_EMCFIL_SDO AS SALDO,
	QT_EMCFIL_MOS AS MOSTRUARIO
FROM
	NSVP.ETQ_MCR_CNT_FIL
WHERE
	CD_EMPGCB = 21 -- Código empresa (21)
	AND CD_FIL IN (525) -- Número da filial
	AND CD_MCR IN (4936280)	-- Código do SKU
WITH UR;


SELECT CD_EMPGCB AS EMPRESA,
CD_FIL AS FILIAL,
CD_MCR AS SKU,
QT_EMCFIL_NOV AS LOJA,
QT_EMCFIL_RSR_VND AS RESERVADO,
QT_EMCFIL_SDO AS SALDO,
QT_EMCFIL_MOS AS MOSTRUARIO
FROM NSVP.ETQ_MCR_CNT_FIL
WHERE CD_MCR IN (4936280)
WITH UR;




SELECT
	t1.cd_amanc,
	T1.DT_CAMANC_INI_VIG,
	T1.DT_CAMANC_FIM_VIG,
	T1.CD_CMC,
	T1.ST_CAMANC_TAX_PCO,
	T1.ST_CAMANC_IRR_DES,
	T1.ST_CAMANC_BLQ_MIN,
	T1.TX_CAMANC_DES
FROM
	CMC_AGP_MCR_ANC T1,
	CMC_TIP_AGP_VLD T2,
	bnd_cmc T3
WHERE
	T1.CD_AMANC = 5060117
	AND T1.CD_EMPGCB = 21
	AND T1.DT_CAMANC_INI_VIG <= CURRENT date
	AND (T1.DT_CAMANC_FIM_VIG IS NULL
		OR T1.DT_CAMANC_FIM_VIG >= CURRENT date)
	AND T2.CD_CMC = T1.CD_CMC
	AND T2.CD_EMPGCB = T1.CD_EMPGCB
	AND T2.CD_TAVCMC IN (1, 2)
	AND T3.CD_CMC = T1.CD_CMC
	AND T3.CD_EMPGCB = T1.CD_EMPGCB
	AND T3.CD_BND IN (1, 2)
WITH UR;






--Busca comercialização de conjunto por filial
SELECT
	T1.CD_AMANC AS SKU,
	T2.cd_fil AS FILIAL,
	T1.CD_CMC AS COD_COMERCIALIZACAO,
	T1.ST_CAMANC_TAX_PCO AS TIPO_DESCONTO_PRATICADO_CONJUNTO,
	T1.DT_CAMANC_INI_VIG AS INICIO_VIGENCIA,
	T1.DT_CAMANC_FIM_VIG AS FIM_VIGENCIA,
	T1.ST_CAMANC_IRR_DES AS GERA_IRREGULARIDADE_DESCONTO,
	T1.ST_CAMANC_BLQ_MIN AS BLOQUEIA_VENDA_ABAIXO_DESC_PERMIT,
	T1.TX_CAMANC_DES
FROM
	NSVP.cmc_AGP_MCR_ANC T1,
	NSVP.CMC_FIL T2,
	NSVP.CMC_TIP_AGP_VLD T3,
	NSVP.BND_CMC T4
WHERE
	T1.CD_AMANC IN (4775627)
	AND T1.CD_EMPGCB = 21
	AND T1.DT_CAMANC_INI_VIG <= CURRENT date
	AND (T1.DT_CAMANC_FIM_VIG IS NULL
		OR T1.DT_CAMANC_FIM_VIG >= CURRENT date)
	AND T2.CD_EMPGCB = 21
	AND T2.CD_FIL IN (1125)
	AND T2.DT_CMCFIL_INI_VIG <= CURRENT date
	AND (T2.DT_CMCFIL_FIM_VIG IS NULL
		OR T2.DT_CMCFIL_FIM_VIG >= CURRENT date)
	AND T1.CD_CMC = T2.CD_CMC
	AND T3.CD_TAVCMC BETWEEN 3 AND 4
	AND T3.CD_CMC = T1.CD_CMC
	AND T3.CD_EMPGCB = T1.CD_EMPGCB
	AND T4.CD_CMC = T1.CD_CMC
	AND T4.CD_EMPGCB = T1.CD_EMPGCB
	AND T4.CD_BND IN (1, 2)
	ORDER BY T2.CD_FIL 
WITH UR;




